# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lms-public-api

on:
  push:
    branches:
      - demo-deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://digitallync.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3de49e4770c84879a0a946e4ef6813e1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b23cefe4312048cb9bf92ca2051bfefc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: digitallync.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3de49e4770c84879a0a946e4ef6813e1 }}/lms-public-api:${{ github.sha }}
        file: ./api/Dockerfile
        context: ./api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lms-public-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_10febab409d44d1b8a57a1d2b7e343a7 }}
        images: 'digitallync.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3de49e4770c84879a0a946e4ef6813e1 }}/lms-public-api:${{ github.sha }}'
